model: 'NCSN'
net: 'refine'
batch_size: 10
input_shape: [256, 256, 2]
data_chns: 'CPLX'

begin_sigma: 1.0
end_sigma: 0.01
anneal_power: 2.
nr_levels: 10
affine_x: False
nonlinearity: 'elu'
nr_filters: 64

lr_warm_up_steps: 1000
lr_start: 0.0003
lr_min: 0.0003
lr_max: 0.0003
lr_max_decay_steps: 2000

seed: 1234
max_keep: 300
max_epochs: 1000
save_interval: 30
saved_name: ncsn_hku
log_folder: /home/gluo/workspace/nlinv/logs

num_prepare: 10
print_loss: True
train_list: /home/gluo/workspace/nlinv/scripts/data/hku_train
test_list: /home/gluo/workspace/nlinv/scripts/data/hku_test

nr_gpu: 3
gpu_id: '0,1,2'
