
model: 'PIXELCNN'
batch_size: 10
input_shape: [256, 256, 2]
nr_resnet: 4
nr_filters: 10
nr_logistic_mix: 10
data_chns: 'CPLX'
dropout_rate: 0.5
itg_interval: 255.0
rlt: 1
layer_norm: False
conditional: False

lr_warm_up_steps: 1000
lr_start: 0.0001
lr_min: 0.0001
lr_max: 0.0001
lr_max_decay_steps: 2000

max_keep: 100
max_epochs: 500
save_interval: 50
saved_name: pixelcnn
log_folder: /home/gluo/workspace/nlinv/logs

num_prepare: 10
print_loss: True
train_list: /home/gluo/workspace/nlinv/scripts/data/hku_train
test_list: /home/gluo/workspace/nlinv/scripts/data/hku_test

nr_gpu: 3
gpu_id: '0,1,2'

# with flip 