## model
model: "SDE"
batch_size: 10
input_shape: [256, 256, 2]
data_chns: 'CPLX'

sigma_max: 1.
sigma_min: 0.001
N: 500
eps: 1.e-5
reduce_mean: False

lr_warm_up_steps: 1000
lr_start: 0.0003
lr_min: 0.0003
lr_max: 0.0003
lr_max_decay_steps: 2000


seed: 1234
net: 'refine'
body: big
nr_filters: 100
nonlinearity: 'elu'
fourier_scale: 16
affine_x: False
attention: True
likelihood_weighting: True

max_keep: 100
max_epochs: 50
save_interval: 5
saved_name: sde_abide
log_folder: /home/gluo/workspace/nlinv_prior/logs

num_thread: 30
print_loss: True
train_list: /home/gluo/workspace/nlinv_prior/data/abide/train
test_list: /home/gluo/workspace/nlinv_prior/data/abide/test

nr_gpu: 4
gpu_id: '0,1,2,3'
